-- 012: notifications, so people hear when someone acts on their work.
--
-- One row per thing that happened to someone: a like on their upload, a review or fix of
-- their transcription, their tag being confirmed or removed by a moderator, someone tagging
-- or transcribing their upload. Rows are written by the API routes right after the action
-- succeeds (src/db/queries/notifications.ts). Nobody is notified about their own action.
--
-- Undoing an action (an unlike, a changed vote) leaves the row alone. Repeating one does
-- not add another: the same person liking the same meme again, after unliking it, is the
-- same news. Likes have a unique index for that; the other kinds are checked on insert.
--
-- Grouping ("alice and 3 others liked your meme") happens when reading, not here.
--
-- tag_name is copied from the tag when the row is written. Removing a tag from its last
-- meme deletes the tag itself, and "a moderator removed your tag" still needs its name.

CREATE TABLE notification (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Who it is for.
  user_id uuid NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN (
    'like',
    'meme_tagged',
    'meme_transcribed',
    'transcription_confirmed',
    'transcription_rejected',
    'transcription_fixed',
    'tag_confirmed',
    'tag_removed'
  )),
  -- Who did it.
  actor_id uuid NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  meme_id uuid NOT NULL REFERENCES meme (id) ON DELETE CASCADE,
  -- The transcription kinds: the version that was reviewed or fixed. meme_transcribed: the
  -- new version.
  transcription_id bigint REFERENCES meme_transcription (id) ON DELETE CASCADE,
  -- The tag kinds.
  tag_id uuid REFERENCES tag (id) ON DELETE SET NULL,
  tag_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- Null until the recipient opens the bell or the notifications page.
  read_at timestamptz,
  CHECK (user_id <> actor_id)
);

-- The list, newest first.
CREATE INDEX notification_user_idx ON notification (user_id, created_at DESC);

-- The unread count in the nav, on every page load.
CREATE INDEX notification_unread_idx ON notification (user_id) WHERE read_at IS NULL;

-- One like notification per person per meme, however often they toggle it.
CREATE UNIQUE INDEX notification_like_key ON notification (user_id, actor_id, meme_id)
  WHERE kind = 'like';
