-- 017: keeping history instead of overwriting or deleting it, a record of what people do,
-- and a log of what moderators do.
--
-- Until now, undoing something erased it. Unliking deleted the like, unsaving the save,
-- taking a tag or a content warning off a meme deleted the row (and a tag's votes with it),
-- and changing a tag vote or a transcription review overwrote the old one. That loses
-- questions worth answering later (how often do people unlike, who keeps flipping their
-- vote) and, for tags, it was a hole in trust: someone whose tag was being downvoted could
-- take it back before it settled, the votes went with it, and user_trust forgot the
-- downvotes had ever happened.
--
-- Soft removal. Every removed row keeps its data and gains removed_at (and removed_by where
-- someone other than the owner can remove it). Every reader filters removed_at IS NULL, so
-- counts, "hasLiked" and the feeds see only live rows.
--
--   meme_like, meme_save, meme_content_warning
--     One row per time it was on: liking again after an unlike inserts a new row rather
--     than reviving the old one, so the history of each like stays intact (when it was
--     given, when taken back). The (meme_id, user_id) primary key becomes a unique index
--     over live rows only, and each table gets a plain id as its key. The id is GENERATED
--     BY DEFAULT so the seed script can load rows with their ids.
--
--   meme_tag
--     Revived rather than duplicated, because meme_tag_vote hangs off (meme_id, tag_id)
--     and the votes are the point. Re-adding a removed tag brings back the same row: same
--     adder, same votes, plus the re-adder's upvote (adding a tag that is already there has
--     always been an upvote). So a tag cannot be washed clean by removing and re-adding it,
--     and someone re-adding a tag another person got wrong takes on none of their votes.
--     Removing no longer deletes a tag left on no meme. The orphan stays; suggestions only
--     offer tags with a live use.
--
-- Trust: votes on a removed tag still count toward its adder's record in user_trust. They
-- were cast on a tag the person really added, and removal (by them or by a moderator)
-- does not make those votes wrong. This is what closes the loophole above. The view needs
-- no change for it: user_trust already joins meme_tag without looking at removed_at, and
-- the votes now survive. Karma and scores, on the other hand, are about what is on the site
-- now, so a removed tag stops counting there like it stops showing.
--
-- History tables. meme_tag_vote and transcription_review stay as they are, one current row
-- per person, which is what scores and the queue read. Every insert and every change of
-- value is also copied to an append-only history table by a trigger, so a flipped vote
-- leaves both votes on record whatever code path wrote it. The existing rows are copied in
-- once, dated when they were first cast; anything before this migration that was later
-- changed is lost already.
--
-- Meme deletion records who deleted it and why (deleted_by, delete_reason). Existing
-- deleted memes keep nulls there: nobody knows.
--
-- event: things people do that leave no other row. Sending, downloading, copying a link,
-- searching (with the result count, so searches that find nothing can be listed), opening
-- a search result, importing a link, uploading, and one "active" row per user per UTC day
-- (app_user.last_active is overwritten, so on its own it cannot say who was active last
-- week). kind is free text with no CHECK, like content warnings: the list lives in
-- src/constants/events.ts and adding a kind needs no migration. data holds whatever that
-- kind needs (query text, site, outcome). A logged-in actor is user_id; a logged-out one is
-- the visitor cookie from migration 015. Both are set null rather than lost if the account
-- goes, so the counts stay right and the person is no longer named.
--
-- moderation_action: one row per thing a moderator or admin did with those powers. Deleting
-- someone else's meme, resolving reports, overriding trust, renaming someone, making or
-- turning off an invite code, and removing someone else's tag, comment or warning. target_id
-- is text because targets are uuids, bigints or names. Read at /admin/log.
--
-- Safe on existing data: only new columns (nullable or defaulted), new tables, new indexes
-- and a swapped primary key on three small tables. Every existing row is live, which is
-- what the null removed_at says. Nothing is deleted or rewritten.

-- Likes, saves and content warnings: a row per time it was on.

ALTER TABLE meme_like DROP CONSTRAINT meme_like_pkey;
ALTER TABLE meme_like
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ADD COLUMN removed_at timestamptz;
CREATE UNIQUE INDEX meme_like_live_key ON meme_like (meme_id, user_id) WHERE removed_at IS NULL;
-- What the old primary key did for cascades and history: every row of one meme.
CREATE INDEX meme_like_meme_idx ON meme_like (meme_id, created_at);

ALTER TABLE meme_save DROP CONSTRAINT meme_save_pkey;
ALTER TABLE meme_save
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ADD COLUMN removed_at timestamptz;
CREATE UNIQUE INDEX meme_save_live_key ON meme_save (meme_id, user_id) WHERE removed_at IS NULL;
CREATE INDEX meme_save_meme_idx ON meme_save (meme_id);

ALTER TABLE meme_content_warning DROP CONSTRAINT meme_content_warning_pkey;
ALTER TABLE meme_content_warning
  ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ADD COLUMN removed_at timestamptz,
  -- Set null rather than lost if that account goes; removed_at still says it was removed.
  ADD COLUMN removed_by uuid REFERENCES app_user (id) ON DELETE SET NULL;
CREATE UNIQUE INDEX meme_content_warning_live_key ON meme_content_warning (meme_id, warning)
  WHERE removed_at IS NULL;
CREATE INDEX meme_content_warning_meme_idx ON meme_content_warning (meme_id);

-- Tags: removed in place, revived in place.

ALTER TABLE meme_tag
  ADD COLUMN removed_at timestamptz,
  ADD COLUMN removed_by uuid REFERENCES app_user (id) ON DELETE SET NULL;

-- Vote and review history.

CREATE TABLE tag_vote_history (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  meme_id uuid NOT NULL REFERENCES meme (id) ON DELETE CASCADE,
  tag_id uuid NOT NULL REFERENCES tag (id) ON DELETE CASCADE,
  -- Set null if the account goes: the vote happened, the person is no longer named.
  voter_id uuid REFERENCES app_user (id) ON DELETE SET NULL,
  vote smallint NOT NULL CHECK (vote IN (-1, 1)),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX tag_vote_history_tag_idx ON tag_vote_history (meme_id, tag_id, created_at);
CREATE INDEX tag_vote_history_voter_idx ON tag_vote_history (voter_id, created_at);

CREATE TABLE transcription_review_history (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  transcription_id bigint NOT NULL REFERENCES meme_transcription (id) ON DELETE CASCADE,
  reviewer_id uuid REFERENCES app_user (id) ON DELETE SET NULL,
  verdict smallint NOT NULL CHECK (verdict IN (-1, 1)),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX transcription_review_history_version_idx
  ON transcription_review_history (transcription_id, created_at);
CREATE INDEX transcription_review_history_reviewer_idx
  ON transcription_review_history (reviewer_id, created_at);

INSERT INTO tag_vote_history (meme_id, tag_id, voter_id, vote, created_at)
SELECT meme_id, tag_id, voter_id, vote, created_at
  FROM meme_tag_vote
 ORDER BY created_at;

INSERT INTO transcription_review_history (transcription_id, reviewer_id, verdict, created_at)
SELECT transcription_id, reviewer_id, verdict, created_at
  FROM transcription_review
 ORDER BY created_at;

-- A new vote, or a vote changed to the other value. Re-sending the same vote is no change.
CREATE FUNCTION record_tag_vote_history() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' OR NEW.vote IS DISTINCT FROM OLD.vote THEN
    INSERT INTO tag_vote_history (meme_id, tag_id, voter_id, vote)
    VALUES (NEW.meme_id, NEW.tag_id, NEW.voter_id, NEW.vote);
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER meme_tag_vote_history
  AFTER INSERT OR UPDATE ON meme_tag_vote
  FOR EACH ROW EXECUTE FUNCTION record_tag_vote_history();

CREATE FUNCTION record_transcription_review_history() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' OR NEW.verdict IS DISTINCT FROM OLD.verdict THEN
    INSERT INTO transcription_review_history (transcription_id, reviewer_id, verdict)
    VALUES (NEW.transcription_id, NEW.reviewer_id, NEW.verdict);
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER transcription_review_history
  AFTER INSERT OR UPDATE ON transcription_review
  FOR EACH ROW EXECUTE FUNCTION record_transcription_review_history();

-- Who deleted a meme, and why.

ALTER TABLE meme
  ADD COLUMN deleted_by uuid REFERENCES app_user (id) ON DELETE SET NULL,
  ADD COLUMN delete_reason text CHECK (char_length(delete_reason) <= 500);

-- Behaviour.

CREATE TABLE event (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  -- A logged-in actor.
  user_id uuid REFERENCES app_user (id) ON DELETE SET NULL,
  -- A logged-out one: the visitor cookie (migration 015).
  visitor_key uuid,
  meme_id uuid REFERENCES meme (id) ON DELETE SET NULL,
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- One kind over time: searches this week, sends per day.
CREATE INDEX event_kind_idx ON event (kind, created_at DESC);

-- One meme's events, and the meme_id foreign key.
CREATE INDEX event_meme_idx ON event (meme_id, created_at DESC) WHERE meme_id IS NOT NULL;

-- One person's events, and the user_id foreign key.
CREATE INDEX event_user_idx ON event (user_id, created_at DESC) WHERE user_id IS NOT NULL;

-- At most one "active" row per user per UTC day, however many requests race to write it.
CREATE UNIQUE INDEX event_active_daily_key ON event (user_id, ((created_at AT TIME ZONE 'UTC')::date))
  WHERE kind = 'active';

-- Moderation.

CREATE TABLE moderation_action (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Set null rather than lost if the moderator's account goes.
  actor_id uuid REFERENCES app_user (id) ON DELETE SET NULL,
  action text NOT NULL,
  -- 'meme', 'comment', 'user' or 'invite'.
  target_type text NOT NULL,
  target_id text NOT NULL,
  reason text,
  data jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- The log, newest first.
CREATE INDEX moderation_action_created_idx ON moderation_action (created_at DESC, id DESC);

-- Everything done to one thing.
CREATE INDEX moderation_action_target_idx ON moderation_action (target_type, target_id, created_at DESC);

CREATE INDEX moderation_action_actor_idx ON moderation_action (actor_id) WHERE actor_id IS NOT NULL;
