--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (422d414)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Cache" (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "ownerUserId" uuid NOT NULL
);


--
-- Name: Like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Like" (
    id integer NOT NULL,
    "memeId" uuid NOT NULL,
    "userId" uuid NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL,
    "deletedAt" timestamp without time zone
);


--
-- Name: Like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Like" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Like_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Meme; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Meme" (
    id uuid NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "deletedAt" timestamp without time zone,
    "uploaderUserId" uuid NOT NULL,
    "s3Key" character varying,
    "contentType" character varying
);


--
-- Name: MemeCache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MemeCache" (
    id integer NOT NULL,
    "memeId" uuid NOT NULL,
    "cacheId" uuid NOT NULL,
    "createdAt" timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: MemeTag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MemeTag" (
    memeid uuid NOT NULL,
    tagid uuid NOT NULL,
    addedby uuid NOT NULL,
    createdat timestamp without time zone DEFAULT now()
);


--
-- Name: MemeTagVote; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MemeTagVote" (
    memeid uuid NOT NULL,
    tagid uuid NOT NULL,
    voterid uuid NOT NULL,
    vote smallint NOT NULL,
    createdat timestamp without time zone DEFAULT now(),
    CONSTRAINT "MemeTagVote_vote_check" CHECK ((vote = ANY (ARRAY['-1'::integer, 1])))
);


--
-- Name: MemeTranscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MemeTranscription" (
    id integer NOT NULL,
    meme_id uuid,
    text text NOT NULL,
    edited_by uuid,
    created_at timestamp without time zone DEFAULT now()
);


--
-- Name: MemeTranscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."MemeTranscription_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: MemeTranscription_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."MemeTranscription_id_seq" OWNED BY public."MemeTranscription".id;


--
-- Name: RefreshToken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RefreshToken" (
    id integer NOT NULL,
    "userId" character varying NOT NULL,
    token character varying NOT NULL
);


--
-- Name: Tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Tag" (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(100) NOT NULL,
    createdat timestamp without time zone DEFAULT now(),
    createdby uuid
);


--
-- Name: User; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."User" (
    id uuid DEFAULT public.uuid_generate_v1() NOT NULL,
    username character varying NOT NULL,
    email character varying NOT NULL,
    "passwordHash" character varying NOT NULL,
    "createdAt" timestamp without time zone,
    "deletedAt" timestamp without time zone,
    role character varying DEFAULT 'user'::character varying NOT NULL,
    "lastActive" timestamp without time zone,
    "avatarS3Key" character varying
);


--
-- Name: memecache_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.memecache_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: memecache_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.memecache_id_seq OWNED BY public."MemeCache".id;


--
-- Name: refreshtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."RefreshToken" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refreshtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MemeCache id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeCache" ALTER COLUMN id SET DEFAULT nextval('public.memecache_id_seq'::regclass);


--
-- Name: MemeTranscription id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTranscription" ALTER COLUMN id SET DEFAULT nextval('public."MemeTranscription_id_seq"'::regclass);


--
-- Name: MemeTagVote MemeTagVote_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTagVote"
    ADD CONSTRAINT "MemeTagVote_pkey" PRIMARY KEY (memeid, tagid, voterid);


--
-- Name: MemeTag MemeTag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTag"
    ADD CONSTRAINT "MemeTag_pkey" PRIMARY KEY (memeid, tagid, addedby);


--
-- Name: MemeTranscription MemeTranscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTranscription"
    ADD CONSTRAINT "MemeTranscription_pkey" PRIMARY KEY (id);


--
-- Name: Tag Tag_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tag"
    ADD CONSTRAINT "Tag_name_key" UNIQUE (name);


--
-- Name: Tag Tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tag"
    ADD CONSTRAINT "Tag_pkey" PRIMARY KEY (id);


--
-- Name: Cache cache_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Cache"
    ADD CONSTRAINT cache_pk PRIMARY KEY (id);


--
-- Name: Cache cache_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Cache"
    ADD CONSTRAINT cache_unique UNIQUE ("ownerUserId");


--
-- Name: Like like_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Like"
    ADD CONSTRAINT like_pk PRIMARY KEY (id);


--
-- Name: Meme meme_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Meme"
    ADD CONSTRAINT meme_pk PRIMARY KEY (id);


--
-- Name: MemeCache memecache_memeid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeCache"
    ADD CONSTRAINT memecache_memeid_key UNIQUE ("memeId");


--
-- Name: MemeCache memecache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeCache"
    ADD CONSTRAINT memecache_pkey PRIMARY KEY (id);


--
-- Name: RefreshToken refreshtoken_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RefreshToken"
    ADD CONSTRAINT refreshtoken_pk PRIMARY KEY (id);


--
-- Name: User user_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT user_pk PRIMARY KEY (id);


--
-- Name: User user_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT user_unique UNIQUE (username);


--
-- Name: User user_unique_1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT user_unique_1 UNIQUE (email);


--
-- Name: MemeTagVote MemeTagVote_memeid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTagVote"
    ADD CONSTRAINT "MemeTagVote_memeid_fkey" FOREIGN KEY (memeid) REFERENCES public."Meme"(id) ON DELETE CASCADE;


--
-- Name: MemeTagVote MemeTagVote_tagid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTagVote"
    ADD CONSTRAINT "MemeTagVote_tagid_fkey" FOREIGN KEY (tagid) REFERENCES public."Tag"(id) ON DELETE CASCADE;


--
-- Name: MemeTagVote MemeTagVote_voterid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTagVote"
    ADD CONSTRAINT "MemeTagVote_voterid_fkey" FOREIGN KEY (voterid) REFERENCES public."User"(id) ON DELETE CASCADE;


--
-- Name: MemeTag MemeTag_addedby_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTag"
    ADD CONSTRAINT "MemeTag_addedby_fkey" FOREIGN KEY (addedby) REFERENCES public."User"(id) ON DELETE CASCADE;


--
-- Name: MemeTag MemeTag_memeid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTag"
    ADD CONSTRAINT "MemeTag_memeid_fkey" FOREIGN KEY (memeid) REFERENCES public."Meme"(id) ON DELETE CASCADE;


--
-- Name: MemeTag MemeTag_tagid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTag"
    ADD CONSTRAINT "MemeTag_tagid_fkey" FOREIGN KEY (tagid) REFERENCES public."Tag"(id) ON DELETE CASCADE;


--
-- Name: MemeTranscription MemeTranscription_edited_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTranscription"
    ADD CONSTRAINT "MemeTranscription_edited_by_fkey" FOREIGN KEY (edited_by) REFERENCES public."User"(id);


--
-- Name: MemeTranscription MemeTranscription_meme_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeTranscription"
    ADD CONSTRAINT "MemeTranscription_meme_id_fkey" FOREIGN KEY (meme_id) REFERENCES public."Meme"(id);


--
-- Name: Tag Tag_createdby_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tag"
    ADD CONSTRAINT "Tag_createdby_fkey" FOREIGN KEY (createdby) REFERENCES public."User"(id);


--
-- Name: Like like_meme_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Like"
    ADD CONSTRAINT like_meme_fk FOREIGN KEY ("memeId") REFERENCES public."Meme"(id) ON DELETE CASCADE;


--
-- Name: Like like_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Like"
    ADD CONSTRAINT like_user_fk FOREIGN KEY ("userId") REFERENCES public."User"(id) ON DELETE CASCADE;


--
-- Name: Meme meme_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Meme"
    ADD CONSTRAINT meme_user_fk FOREIGN KEY ("uploaderUserId") REFERENCES public."User"(id);


--
-- Name: MemeCache memecache_cacheid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeCache"
    ADD CONSTRAINT memecache_cacheid_fkey FOREIGN KEY ("cacheId") REFERENCES public."Cache"(id) ON DELETE CASCADE;


--
-- Name: MemeCache memecache_memeid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MemeCache"
    ADD CONSTRAINT memecache_memeid_fkey FOREIGN KEY ("memeId") REFERENCES public."Meme"(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


